# Change these first
owner: LowlandwasTaken # Your GitHub organization or username, where this repository lives
repo: BreathFM-Status # The name of this repository

sites:
  - name: Mainstream
    url: 88.99.104.157
    port: 8020
    check: "tcp-ping"
    ipv6: false
  - name: InTheMiX
    url: 88.99.104.157
    port: 8030
    check: "tcp-ping"
    ipv6: false
  - name: WinterMix
    url: 88.99.104.157
    port: 8060
    check: "tcp-ping"
    ipv6: false
  - name: Chill
    url: 88.99.104.157
    port: 8070
    check: "tcp-ping"
    ipv6: false
  - name: SummerMix
    url: 88.99.104.157
    port: 8040
    check: "tcp-ping"
    ipv6: false


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.breathfm.de
  logoUrl: https://breathfm.de/static/media/Logo.4eaca830821acccb7df5490a622f2bb4.svg
  name: BreathFM Status
  themeUrl: https://status.breathfm.de/custom.css
  introTitle: "**BreathFM** ist ein Webradio aus der Schweiz welches in die ganze Welt streamt!"
  introMessage: Hier seht ihr den Status unserer Sender!
  customBodyHtml: <div class="bg-image"></div>
  favicon: https://r2.e-z.host/7e095bd3-bee6-4515-afab-65c01b5c886c/srk5mbe3.png
  metaTags:
    - name: "theme-color"
      content: "#292a2a"
    - name: "twitter:title"
      content: "BreathFM Status"
    - name: "og:title"
      content: "BreathFM Status"
    - name: "og:description"
      content: "Status der Radio-Sender von BreathFM!"
    - name: "description"
      content: "Status der Radio-Sender von BreathFM!"
  navbar:
    - title: BreathFM
      href: https://breathfm.de/
  links:
    - rel: stylesheet
      href: https://status.breathfm.de/stylesheet.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
